import logo from "../assets/images/logo.png"
import img1 from "../assets/images/cosmetic.jpg"
import img2 from "../assets/images/cosmetic2.jpg"
import img3 from "../assets/images/cosmetic3.avif"
import serum from "../assets/images/face serum.jpg"
import eyeshadow from "../assets/images/eyeshadow.jpg"
import foundation from "../assets/images/foundation.webp"
import highlighter from "../assets/images/highlighter.jpg"
import lipstick from "../assets/images/lipstick.jpg"
import mascara from "../assets/images/mascara.webp"
import blush from "../assets/images/blush.jpg"
import eyebrow from "../assets/images/eyebrow.jpg"
import liptint from "../assets/images/lip tint.webp"
import primer from "../assets/images/primer.jpg"
import settingspray from "../assets/images/setting spray.jpg"
import toner from "../assets/images/toner.jpg"
import courosel from "../assets/images/courosel1.webp"
import courosel2 from "../assets/images/courosel2.webp"
import sunscreen from "../assets/images/sunscreen.webp"
import aboutpic1 from "../assets/images/about1.avif"
import aboutpic2 from "../assets/images/about2.avif"
import lipstickbg from "../assets/images/lipstickbg.avif"
import charlotte from "../assets/images/charlotte.avif"
import kaybeauty from "../assets/images/Kayhydralipstick.avif"
import lakmeforever from "../assets/images/lakmeforever.avif"
import maybelline from "../assets/images/maybelline.avif"
import nykalipstick from "../assets/images/nykalipstick.avif"
import mars from "../assets/images/mars.avif"
import swiss from "../assets/images/swiss.avif"
import mac from "../assets/images/mac.avif"
import lipstickbanner from "../assets/images/lipstickbanner.webp"
import nybae from "../assets/images/nybae.webp"
import maybellinestay from "../assets/images/maybellinestay.webp"
import sugar from "../assets/images/sugar.webp"
import blueheaven from "../assets/images/blueheaven.webp"
import swissbeauty from "../assets/images/swissbeauty.webp"
import renee from "../assets/images/renee.webp"
import insight from "../assets/images/insight.webp"
import swiss3 from "../assets/images/swiss3.webp"
import blushbg from "../assets/images/blushbg.webp"
import nybaeblush from "../assets/images/nybaeblush.webp"
import maybellineblush from "../assets/images/maybellineblush.webp"
import lakmeblush from "../assets/images/lakmeblush.webp"
import marsblush from "../assets/images/marsblush.webp"
import blushbg2 from "../assets/images/blushbg2.avif"
import nybaesunset from "../assets/images/nybaesunset.webp"
import insightblush from "../assets/images/insightblsh.webp"
import swissblush from "../assets/images/swissblush.webp"
import maybellinefitme from "../assets/images/maybellinefitme.webp"
import foundationbg from "../assets/images/foundationbg.avif"
import kayfoundation from "../assets/images/kayfoundation.avif"
import maybellinefoundation from "../assets/images/maybellinefoundation.avif"
import lakmefoundation from "../assets/images/lakmefoundation.avif"
import charlottefoundation  from "../assets/images/charlottefoundation.avif"
import esteelauder  from "../assets/images/esteelauder.avif"
import hudabeauty  from "../assets/images/hudabeauty.avif"
import nykaafoundation  from "../assets/images/nykaafoundation.avif"
import smashboxfoundation  from "../assets/images/smashbox foundation.avif"
import Eyeshadowbg from "../assets/images/Eyeshadowbg.webp"
import marseyeshadow from "../assets/images/marseyeshadow.webp"
import swisseyeshadow from "../assets/images/swisseyeshadow.webp"
import hilaryeyeshadow from "../assets/images/hilaryeyeshadow.webp"
import marsdanceeyeshadow from "../assets/images/marsdanceeyeshadow.webp"
import swissbeautyultimate from "../assets/images/swissbeautyultimate.webp"
import rhodaeyeshadow from "../assets/images/rhodaeyeshadow.webp"
import maybellineeyeshadow from "../assets/images/maybellineeyeshadow.webp"
import blueheaveneyeshadow from "../assets/images/blueheaveneyeshadow.webp"
import eyeshadowbg2 from "../assets/images/eyeshadowbg2.avif"
import contactbg from "../assets/images/contactbg.webp"


const Img = {
    logo,img1,img2,img3,serum,eyeshadow,aboutpic1,aboutpic2,courosel,foundation,highlighter,lipstick,mascara,blush,eyebrow,liptint,primer,settingspray,toner,courosel2,sunscreen,lipstickbg,lipstickbanner,charlotte,kaybeauty,lakmeforever,maybelline,nykalipstick,mac,mars,swiss,nybae,maybellinestay,sugar,blueheaven,swissbeauty,renee,insight,swiss3,blushbg,nybaeblush,maybellineblush,lakmeblush,marsblush,blushbg2,nybaesunset,insightblush,swissblush,maybellinefitme,foundationbg,kayfoundation,maybellinefoundation,lakmefoundation,charlottefoundation,
    esteelauder,hudabeauty,nykaafoundation,smashboxfoundation,Eyeshadowbg,marseyeshadow,swisseyeshadow,hilaryeyeshadow,marsdanceeyeshadow,swissbeautyultimate,rhodaeyeshadow,maybellineeyeshadow,blueheaveneyeshadow,eyeshadowbg2,contactbg
}

export default Img